### ISSUE TITLE
MariaDB plug-in always shows "mariadb" as source program

### ISSUE THREAD

**Issue by Tal-Daniel** [IBM/universal-connectors#156]
**Describe the bug**
When using MariaDB plug-in within Guardium, the reports show the source program as "MARIADB", no matter what, instead of defaulting to empty field, when no info exists in the MariaDB audit logs. 

**To Reproduce**
Steps to reproduce the behavior on developer machine:
1. Download the plug-in zip and Install it in Logstash (follow README > [setup dev environment](https://github.com/IBM/universal-connectors/tree/main/filter-plugin/logstash-filter-mariadb-guardium#set-up-dev-environment), first)
2. Run Logstash with this plugin and the test configuration that resides within the plug-in's folder (see README > [Run on local Logstash](https://github.com/IBM/universal-connectors/tree/main/filter-plugin/logstash-filter-mariadb-guardium#run-on-local-logstash)). This will generate an event you can test. Alternatively, run the Java code and add a unit test.
3. Check the source program field within the POJO of the Logstash dummy output plugin 
4. sourceProgram contains "mariadb", instead of being empty. 

**Expected behavior**
Correct source program, or if not available in audit log, empty field, as source program is not a mandatory field within the Guardium Record object.

**Environment (please complete the following information):**
 - Product: Guardium Data Protection
 - Version 11.4

**Additional context**
Looks like a minor fix could solve this by not filling the source program parameter [here](https://github.com/IBM/universal-connectors/blob/main/filter-plugin/logstash-filter-mariadb-guardium/src/main/java/com/ibm/guardium/mariadb/ParserHelper.java#L103), instead of putting a constant

**Comment by ofer-haim** [comment]
MariaDB bug was adjusted to be consistent with the rest of the plugins behavior. Hence, closing this
