### ISSUE TITLE
No access enrollmentID  universal connector guardium

### ISSUE THREAD

**Issue by Rdecoster** [IBM/universal-connectors#259]
For configuring the universal connector in the guardian. https://github.com/IBM/universal-connectors/tree/main/filter-plugin/logstash-filter-azure-sql-guardium
 step 5  requires an enrollment id from azure portal enterprise. where it is later used in step 7 configuring th input information from https://github.com/IBM/universal-connectors/blob/main/filter-plugin/logstash-filter-azure-sql-guardium/azureSQLJDBC.conf line 23 No one in my group including my administrator/owner for the azure account has an enrollment id for the account. as it is not an enterprise azure account.  is it possible to include instructions for subscription id or tenant id?

**Comment by Tal-Daniel** [comment]
@PratikshaSonawane @ofer-haim

**Comment by ofer-haim** [comment]
I'm not sure it can work without Azure enterprise account. There are a couple of dbs that doesn't allow monitoring without free/trial accounts. 
If this is a requirement, need to pass it to Guardium PM team so that dev will will prioritize tests and adjustments if needed

**Comment by Rdecoster** [comment]
@ofer-haim @Tal-Daniel 
I figured it out. 
In Azure, the terminology and features related to billing and enrollment have evolved over time. To clarify the current terminology:

Enrollment ID: Previously used to identify an Azure Enterprise Agreement, the use of the term "Enrollment ID" is no longer prevalent in the Azure portal.

Billing Account ID: The Billing Account ID is a unique identifier associated with an Azure subscription's billing. It is now commonly used to refer to the ID associated with the billing account. This is the number you will need to use. I have seen numbers between 6-8 characters long be valid. 

To find the Billing Account ID or Enrollment ID (if applicable) in the Azure portal, follow these steps:

Sign in to the Azure portal (portal.azure.com) with an account that has the necessary permissions.

Navigate to the "Billing" blade, which provides an overview of your billing information.

Locate the "Overview" or "Account summary" section, where you should find the Billing Account ID or Enrollment ID. It may be listed next to your username or in a separate column, depending on the portal's layout.

If you have access to the modern billing blade, click on the "All scopes" tab. The number in parentheses next to your username can serve as your Enrollment ID or Billing Account ID.

I hope this helps.

**Comment by ofer-haim** [comment]
Thank you @Rdecoster. We will run a few tests and document this accordingly
